services:
  db:
    image: postgres:15.8
    restart: always
    container_name: usher_web_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "2345:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
